# Generated by Django 3.2.3 on 2021-11-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeds',
            name='caption',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='feedTitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='imgFeed',
            field=models.ImageField(blank=True, upload_to='upload/images'),
        ),
    ]
