# Generated by Django 3.2.3 on 2021-11-16 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_chatting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 16, 12, 0, 35, 799737), null=True),
        ),
    ]
